// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtU01XA7RBbvgIqqa087rz6IAv1jwuDZE',
    appId: '1:1059568358871:web:babaf0a4634f74d06ee792',
    messagingSenderId: '1059568358871',
    projectId: 'medipanda-d98c0',
    authDomain: 'medipanda-d98c0.firebaseapp.com',
    storageBucket: 'medipanda-d98c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKtoVNFZrOvKBXlfT_huMxmYJAYyPsvY',
    appId: '1:1059568358871:android:f3af097d95f66a866ee792',
    messagingSenderId: '1059568358871',
    projectId: 'medipanda-d98c0',
    storageBucket: 'medipanda-d98c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChY5-O1PTVYtIiQOv2SfLQ7pCCkF0UHQ8',
    appId: '1:1059568358871:ios:ec6687c0655d66286ee792',
    messagingSenderId: '1059568358871',
    projectId: 'medipanda-d98c0',
    storageBucket: 'medipanda-d98c0.firebasestorage.app',
    iosBundleId: 'com.example.medipanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChY5-O1PTVYtIiQOv2SfLQ7pCCkF0UHQ8',
    appId: '1:1059568358871:ios:ec6687c0655d66286ee792',
    messagingSenderId: '1059568358871',
    projectId: 'medipanda-d98c0',
    storageBucket: 'medipanda-d98c0.firebasestorage.app',
    iosBundleId: 'com.example.medipanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtU01XA7RBbvgIqqa087rz6IAv1jwuDZE',
    appId: '1:1059568358871:web:76edfeccca79c00c6ee792',
    messagingSenderId: '1059568358871',
    projectId: 'medipanda-d98c0',
    authDomain: 'medipanda-d98c0.firebaseapp.com',
    storageBucket: 'medipanda-d98c0.firebasestorage.app',
  );
}
